disabled = false
locale = "fa"
label = "فارسی"
weight = 2
title = "Alex Tz"

[params]
  displayName = "فارسی"
  isoCode = "fa"
  rtl = true
  dateFormat = "2 January 2006"
  description = "وبلاگ و وبسایت Alex Tz"

[params.author]
  name = "Alex Tz"
  email = "mstalebizadeh@gmail.com"
  image = "img/avatar.jpg"
  imageQuality = 96
  headline = "توسعه‌دهنده فلاتر"
  bio = "توسعه‌دهنده فلاتر، مشارکت‌کننده متن‌باز، وبلاگ‌نویس فنی"
  links = [
    { email = "mailto:mstalebizade@gmail.com" },
    { github = "https://github.com/salehtz" },
    { linkedin = "https://linkedin.com/in/salehtz" },
    { x-twitter = "https://twitter.com/mrtzdev" },
    { telegram = "https://t.me/anonytz" },
    { instagram = "https://instagram.com/mr_tz.dev" },
  ]
